<?php

namespace ContainerQzRir0v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P6p5NRHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P6p5NRH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P6p5NRH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoriesController::delete' => ['privates', '.service_locator.wLJWiJM', 'get_ServiceLocator_WLJWiJMService', true],
            'App\\Controller\\CategoriesController::edit' => ['privates', '.service_locator.wLJWiJM', 'get_ServiceLocator_WLJWiJMService', true],
            'App\\Controller\\CategoriesController::index' => ['privates', '.service_locator.Ksprajg', 'get_ServiceLocator_KsprajgService', true],
            'App\\Controller\\CategoriesController::new' => ['privates', '.service_locator.Ksprajg', 'get_ServiceLocator_KsprajgService', true],
            'App\\Controller\\CategoriesController::show' => ['privates', '.service_locator.gFHHwHB', 'get_ServiceLocator_GFHHwHBService', true],
            'App\\Controller\\ContentsController::delete' => ['privates', '.service_locator.d0_1Peq', 'get_ServiceLocator_D01PeqService', true],
            'App\\Controller\\ContentsController::edit' => ['privates', '.service_locator.d0_1Peq', 'get_ServiceLocator_D01PeqService', true],
            'App\\Controller\\ContentsController::index' => ['privates', '.service_locator.hmYtjsU', 'get_ServiceLocator_HmYtjsUService', true],
            'App\\Controller\\ContentsController::new' => ['privates', '.service_locator.hmYtjsU', 'get_ServiceLocator_HmYtjsUService', true],
            'App\\Controller\\ContentsController::show' => ['privates', '.service_locator.xKAokjN', 'get_ServiceLocator_XKAokjNService', true],
            'App\\Controller\\ImagesController::delete' => ['privates', '.service_locator.OooJHMV', 'get_ServiceLocator_OooJHMVService', true],
            'App\\Controller\\ImagesController::edit' => ['privates', '.service_locator.OooJHMV', 'get_ServiceLocator_OooJHMVService', true],
            'App\\Controller\\ImagesController::index' => ['privates', '.service_locator.mHNuZus', 'get_ServiceLocator_MHNuZusService', true],
            'App\\Controller\\ImagesController::new' => ['privates', '.service_locator.mHNuZus', 'get_ServiceLocator_MHNuZusService', true],
            'App\\Controller\\ImagesController::show' => ['privates', '.service_locator.ag89WnJ', 'get_ServiceLocator_Ag89WnJService', true],
            'App\\Controller\\PagesController::delete' => ['privates', '.service_locator.uCQHI.f', 'get_ServiceLocator_UCQHI_FService', true],
            'App\\Controller\\PagesController::edit' => ['privates', '.service_locator.uCQHI.f', 'get_ServiceLocator_UCQHI_FService', true],
            'App\\Controller\\PagesController::index' => ['privates', '.service_locator.nlXvkyh', 'get_ServiceLocator_NlXvkyhService', true],
            'App\\Controller\\PagesController::new' => ['privates', '.service_locator.nlXvkyh', 'get_ServiceLocator_NlXvkyhService', true],
            'App\\Controller\\PagesController::show' => ['privates', '.service_locator.JncVs31', 'get_ServiceLocator_JncVs31Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CategoriesController:delete' => ['privates', '.service_locator.wLJWiJM', 'get_ServiceLocator_WLJWiJMService', true],
            'App\\Controller\\CategoriesController:edit' => ['privates', '.service_locator.wLJWiJM', 'get_ServiceLocator_WLJWiJMService', true],
            'App\\Controller\\CategoriesController:index' => ['privates', '.service_locator.Ksprajg', 'get_ServiceLocator_KsprajgService', true],
            'App\\Controller\\CategoriesController:new' => ['privates', '.service_locator.Ksprajg', 'get_ServiceLocator_KsprajgService', true],
            'App\\Controller\\CategoriesController:show' => ['privates', '.service_locator.gFHHwHB', 'get_ServiceLocator_GFHHwHBService', true],
            'App\\Controller\\ContentsController:delete' => ['privates', '.service_locator.d0_1Peq', 'get_ServiceLocator_D01PeqService', true],
            'App\\Controller\\ContentsController:edit' => ['privates', '.service_locator.d0_1Peq', 'get_ServiceLocator_D01PeqService', true],
            'App\\Controller\\ContentsController:index' => ['privates', '.service_locator.hmYtjsU', 'get_ServiceLocator_HmYtjsUService', true],
            'App\\Controller\\ContentsController:new' => ['privates', '.service_locator.hmYtjsU', 'get_ServiceLocator_HmYtjsUService', true],
            'App\\Controller\\ContentsController:show' => ['privates', '.service_locator.xKAokjN', 'get_ServiceLocator_XKAokjNService', true],
            'App\\Controller\\ImagesController:delete' => ['privates', '.service_locator.OooJHMV', 'get_ServiceLocator_OooJHMVService', true],
            'App\\Controller\\ImagesController:edit' => ['privates', '.service_locator.OooJHMV', 'get_ServiceLocator_OooJHMVService', true],
            'App\\Controller\\ImagesController:index' => ['privates', '.service_locator.mHNuZus', 'get_ServiceLocator_MHNuZusService', true],
            'App\\Controller\\ImagesController:new' => ['privates', '.service_locator.mHNuZus', 'get_ServiceLocator_MHNuZusService', true],
            'App\\Controller\\ImagesController:show' => ['privates', '.service_locator.ag89WnJ', 'get_ServiceLocator_Ag89WnJService', true],
            'App\\Controller\\PagesController:delete' => ['privates', '.service_locator.uCQHI.f', 'get_ServiceLocator_UCQHI_FService', true],
            'App\\Controller\\PagesController:edit' => ['privates', '.service_locator.uCQHI.f', 'get_ServiceLocator_UCQHI_FService', true],
            'App\\Controller\\PagesController:index' => ['privates', '.service_locator.nlXvkyh', 'get_ServiceLocator_NlXvkyhService', true],
            'App\\Controller\\PagesController:new' => ['privates', '.service_locator.nlXvkyh', 'get_ServiceLocator_NlXvkyhService', true],
            'App\\Controller\\PagesController:show' => ['privates', '.service_locator.JncVs31', 'get_ServiceLocator_JncVs31Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CategoriesController::delete' => '?',
            'App\\Controller\\CategoriesController::edit' => '?',
            'App\\Controller\\CategoriesController::index' => '?',
            'App\\Controller\\CategoriesController::new' => '?',
            'App\\Controller\\CategoriesController::show' => '?',
            'App\\Controller\\ContentsController::delete' => '?',
            'App\\Controller\\ContentsController::edit' => '?',
            'App\\Controller\\ContentsController::index' => '?',
            'App\\Controller\\ContentsController::new' => '?',
            'App\\Controller\\ContentsController::show' => '?',
            'App\\Controller\\ImagesController::delete' => '?',
            'App\\Controller\\ImagesController::edit' => '?',
            'App\\Controller\\ImagesController::index' => '?',
            'App\\Controller\\ImagesController::new' => '?',
            'App\\Controller\\ImagesController::show' => '?',
            'App\\Controller\\PagesController::delete' => '?',
            'App\\Controller\\PagesController::edit' => '?',
            'App\\Controller\\PagesController::index' => '?',
            'App\\Controller\\PagesController::new' => '?',
            'App\\Controller\\PagesController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CategoriesController:delete' => '?',
            'App\\Controller\\CategoriesController:edit' => '?',
            'App\\Controller\\CategoriesController:index' => '?',
            'App\\Controller\\CategoriesController:new' => '?',
            'App\\Controller\\CategoriesController:show' => '?',
            'App\\Controller\\ContentsController:delete' => '?',
            'App\\Controller\\ContentsController:edit' => '?',
            'App\\Controller\\ContentsController:index' => '?',
            'App\\Controller\\ContentsController:new' => '?',
            'App\\Controller\\ContentsController:show' => '?',
            'App\\Controller\\ImagesController:delete' => '?',
            'App\\Controller\\ImagesController:edit' => '?',
            'App\\Controller\\ImagesController:index' => '?',
            'App\\Controller\\ImagesController:new' => '?',
            'App\\Controller\\ImagesController:show' => '?',
            'App\\Controller\\PagesController:delete' => '?',
            'App\\Controller\\PagesController:edit' => '?',
            'App\\Controller\\PagesController:index' => '?',
            'App\\Controller\\PagesController:new' => '?',
            'App\\Controller\\PagesController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
