<?php

namespace ContainerQzRir0v;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OooJHMVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OooJHMV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OooJHMV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'image' => ['privates', '.errored..service_locator.OooJHMV.App\\Entity\\Images', NULL, 'Cannot autowire service ".service_locator.OooJHMV": it references class "App\\Entity\\Images" but no such service exists.'],
            'imagesRepository' => ['privates', 'App\\Repository\\ImagesRepository', 'getImagesRepositoryService', true],
        ], [
            'image' => 'App\\Entity\\Images',
            'imagesRepository' => 'App\\Repository\\ImagesRepository',
        ]);
    }
}
