<?php

namespace ContainerHZVyIxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D01PeqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d0_1Peq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d0_1Peq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'content' => ['privates', '.errored..service_locator.d0_1Peq.App\\Entity\\Contents', NULL, 'Cannot autowire service ".service_locator.d0_1Peq": it references class "App\\Entity\\Contents" but no such service exists.'],
            'contentsRepository' => ['privates', 'App\\Repository\\ContentsRepository', 'getContentsRepositoryService', true],
        ], [
            'content' => 'App\\Entity\\Contents',
            'contentsRepository' => 'App\\Repository\\ContentsRepository',
        ]);
    }
}
