<?php

namespace ContainerHZVyIxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NlXvkyhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nlXvkyh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nlXvkyh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pagesRepository' => ['privates', 'App\\Repository\\PagesRepository', 'getPagesRepositoryService', true],
        ], [
            'pagesRepository' => 'App\\Repository\\PagesRepository',
        ]);
    }
}
