<?php

namespace ContainerHZVyIxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XKAokjNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xKAokjN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xKAokjN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'content' => ['privates', '.errored..service_locator.xKAokjN.App\\Entity\\Contents', NULL, 'Cannot autowire service ".service_locator.xKAokjN": it references class "App\\Entity\\Contents" but no such service exists.'],
        ], [
            'content' => 'App\\Entity\\Contents',
        ]);
    }
}
