<?php

namespace ContainerHZVyIxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContents3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xKAokjN.App\Entity\Contents' shared service.
     *
     * @return \App\Entity\Contents
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xKAokjN": it references class "App\\Entity\\Contents" but no such service exists.');
    }
}
