<?php

namespace ContainerHZVyIxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImages3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cIhqKE1.App\Entity\Images' shared service.
     *
     * @return \App\Entity\Images
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cIhqKE1": it references class "App\\Entity\\Images" but no such service exists.');
    }
}
