<?php

namespace ContainerHZVyIxL;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPages3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uCQHI.f.App\Entity\Pages' shared service.
     *
     * @return \App\Entity\Pages
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uCQHI.f": it references class "App\\Entity\\Pages" but no such service exists.');
    }
}
