<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.


if (\class_exists(\ContainerHZVyIxL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHZVyIxL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHZVyIxL.legacy');


    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {

    \class_alias(\ContainerHZVyIxL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHZVyIxL\App_KernelDevDebugContainer([
    'container.build_hash' => 'HZVyIxL',
    'container.build_id' => '8f198e5e',
    'container.build_time' => 1670317324,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHZVyIxL');

