<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2uqncUV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2uqncUV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2uqncUV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2uqncUV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2uqncUV\App_KernelDevDebugContainer([
    'container.build_hash' => '2uqncUV',
    'container.build_id' => 'e15314ce',
    'container.build_time' => 1670410002,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2uqncUV');
