<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDEEHpTZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDEEHpTZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDEEHpTZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDEEHpTZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDEEHpTZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'DEEHpTZ',
    'container.build_id' => '1bbb0888',
    'container.build_time' => 1670253367,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDEEHpTZ');
